blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("create/", views.PostCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.PostUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.PostDeleteView.as_view(), name="delete"),

    # url(r"^$", views.PostListView.as_view(), name="post_list"),
    # url(r"^about", views.AboutView.as_view(), name="about"),
    # url(r"^post/(?P<pk>\d+)/$",views.PostDetailView.as_view(),name="post_detail"),
    # url(r"^post/(?P<pk>\d+)/edit",views.PostUpdateView.as_view(),name="post_update"),
    # url(r"^post/(?P<pk>\d+)/delete",views.PostDeleteView.as_view(),name="post_delete"),
    # url(r"^post/create/$",views.PostCreateView.as_view(),name="post_create"),
    # url(r"^draft",views.DraftView.as_view(),name="draft"),
    # url(r"^post/(?P<pk>\d+)/comment",views.add_comment,name="comment"),
    # url(r"^comment/(?P<pk>\d+)/approve/$",views.comment_approve,name="comment_approve"),
    # url(r"^comment/(?P<pk>\d+)/remove/$",views.comment_remove,name="comment_remove"),
    # url(r"^post/(?P<pk>\d+)/publish/$",views.publish,name="post_publish")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
    path("user/", include(("user.urls", "user"), namespace="user")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("register/", views.UserRegistrationView.as_view(), name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User


class Post(models.Model):
    """Blog post model."""

    class Status(models.TextChoices):
        """Status of blog post."""

        DRAFT = "DRAFT", _("Draft")
        PUBLISH = "PUBLISH", _("Publish")

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    title = models.CharField(max_length=255, blank=False, null=False)
    text = models.TextField(blank=False, null=False)
    status = models.CharField(max_length=7, choices=Status, default=Status.DRAFT)
    creation_date = models.DateTimeField(auto_now_add=True)
    updation_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True)

    class Meta:
        db_table = "posts"

    @property
    def is_published(self) -> bool:
        """Check is blog is published."""
        return self.published_date is not None

    def save(self, *args, **kwargs):
        """
        Save the instance.

        It also checks if the blog post has been published or not.
        """
        if not self.is_published and self.status == self.Status.PUBLISH:
            self.published_date = timezone.now()

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Comment(models.Model):
    """Comment of blog post."""

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commentor")
    text = models.TextField(max_length=510)
    creation_date = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = "comments"

    def __str__(self):
        return self.text

blog/forms.py
from django import forms

from . import models


class PostCreateForm(forms.ModelForm):
    """Form for post creation."""

    class Meta:
        model = models.Post
        fields = ("title", "text")


class PostUpdateForm(forms.ModelForm):
    """Form for post updation."""

    class Meta:
        model = models.Post
        fields = ("title", "text", "status")


class PostCommentForm(forms.ModelForm):
    """Form for post comments"""

    class Meta:
        model = models.Comment
        fields = ("text",)

blog/views.py
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin

from . import models
from . import forms

# from django.shortcuts import render,get_object_or_404,redirect
# from django.http import HttpResponse,HttpResponseRedirect
# from django.urls import reverse,reverse_lazy
# from django.contrib.auth.decorators import login_required
# from django.contrib.auth import login,logout,authenticate
# from django.views.generic import TemplateView, DetailView, ListView, UpdateView, DeleteView, CreateView

# from . import forms


class PostListView(ListView):
    """Posts list view containing posts that are published."""

    model = models.Post
    context_object_name = "posts"
    template_name = "blog/list.html"
    queryset = models.Post.objects.all().filter(status=models.Post.Status.PUBLISH)


class PostCreateView(LoginRequiredMixin, CreateView):
    """Post create view."""

    model = models.Post
    form_class = forms.PostCreateForm
    template_name = "blog/create.html"

    def get_success_url(self) -> str:
        return reverse("blog:detail", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class PostDetailView(DetailView, FormView):
    """Post details view."""

    model = models.Post
    context_object_name = "post"
    form_class = forms.PostCommentForm
    template_name = "blog/detail.html"

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs["comments"] = self.object.comments.all()
        kwargs['form'] = self.get_form()
        return kwargs

    def get_success_url(self) -> str:
        return reverse("blog:detail", kwargs={"pk": self.object.pk})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = self.object
        comment.user = self.request.user
        comment.save()
        return redirect(self.get_success_url())


class PostUpdateView(LoginRequiredMixin, UpdateView):
    """Draft view of the post."""

    model = models.Post
    form_class = forms.PostUpdateForm
    context_object_name = "post"
    template_name = "blog/update.html"

    def get_success_url(self) -> str:
        return reverse("blog:detail", kwargs={"pk": self.object.pk})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    """Delete view of the post."""

    model = models.Post
    template_name = "blog/delete.html"
    context_object_name = "post"
    success_url = reverse_lazy("user:dashboard")


# class CommentCreateView(LoginRequiredMixin, CreateView):
#     """Create user comments."""

#     model = models.Comment
#     template_name = "blog/delete.html"

#     def get_success_url(self) -> str:
#         return reverse("blog:detail", kwargs={"pk": self.object.post.pk})


# def user_login(request):
#     context = {}

#     if request.method == "POST":
#         username = request.POST.get("username")
#         password = request.POST.get("password")
#         if user := authenticate(username=username, password=password):
#             if user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect("/")
#             else:
#                 return HttpResponse("blog/post_list.html")
#         else:
#             return render(request,"registeration/login.html",{})

#     else:
#         return render(request,"registeration/login.html",{})

# @login_required
# def user_logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse("blog:post_list"))

# @login_required
# def publish(request,pk):
#     post = get_object_or_404(Post,pk=pk)
#     post.publish()
#     post.save()
#     return HttpResponseRedirect("/draft")

# class AboutView(TemplateView):
#     template_name = "blog/post_about.html"


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "blog/post_detail.html"

# class PostCreateView(LoginRequiredMixin,CreateView):
#     login_url = "/login/"
#     redirect_field_name = "blog:post_detail"
#     form_class = PostForm
#     model = Post
#     template_name = "blog/post_create.html"

# class PostUpdateView(LoginRequiredMixin,UpdateView):
#     model = Post
#     template_name = "blog/post_update.html"

#     login_url = "/login/"
#     redirect_field_name = "blog/post_detail.html"
#     form_class = PostForm

# class PostDeleteView(LoginRequiredMixin,DeleteView):
#     model = Post
#     success_url = reverse_lazy("blog:post_list")


# class DraftView(LoginRequiredMixin,ListView):
#     model = Post
#     context_object_name = "DraftL"
#     template_name = "blog/post_draft_list.html"

#     login_url = "/login/"
#     redirect_field_name = "blog/post_list.html"

#     def get_queryset(self):
#         return Post.objects.filter(published_date__isnull=True).order_by("published_date")

# #######################################################################
# ######################  COMMENTS  #####################################


# def add_comment(request,pk):
#     post = get_object_or_404(Post,pk=pk)

#     if request.method == "POST":
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.post = post
#             comment.author=request.user.username
#             comment.save()

#             return redirect("blog:post_detail",pk=post.pk)

#     else:
#         form = CommentForm()
#         return render(request,"blog/post_detail.html",{"form1":form,"post":post})

# @login_required
# def comment_approve(request,pk):
#     comment = get_object_or_404(Comment,pk=pk)
#     comment.approve()
#     pks=comment.post.pk
#     return redirect("blog:post_detail",pk=pks)

# @login_required
# def comment_remove(request,pk):
#     comment = get_object_or_404(Comment,pk=pk)
#     post_pk = comment.post.pk
#     comment.delete()
#     return redirect("blog:post_detail",pk=post_pk)

templates/blog/comment_post.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Add Comment">
<!--                <a href="{% url 'blog:post_detail' pk=post.pk %}" class="btn btn-primary">Cancel</a>-->
            </form>
        </div>
    </div>
{% endblock %}

templates/blog/create.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}Blog | create{% endblock title %}

{% block content %}
<div class="container mt-5" style="max-width: 48rem">
    <div class="card">

        <h3 class="card-header fw-bold text-center">Create new blog</h3>

        <div class="card-body">
            <form action="{% url "blog:create" %}" method="post">
                {% csrf_token %}

				<div class="mb-3">
					<div class="form-text text-danger-emphasis">
						{% for error in form.non_field_errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
				</div>

                <div class="mb-3">
                    <label for="id_title" class="form-text">Title</label>
                    <input type="text" name="title" id="id_title" class="form-control" autocomplete="off" maxlength="{{ form.title.meta.maxlength }}" required>
                    <div id="id_title_errors" class="form-text text-danger-emphasis">
						{% for error in form.title.errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
                </div>

                <div class="mb-3">
                    <label for="id_text" class="form-text">Content</label>
                    <textarea name="text" id="id_text" class="form-control" rows="12" required></textarea>
                    <div id="id_text_errors" class="form-text text-danger-emphasis">
						{% for error in form.text.errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
                </div>

				<button type="submit" class="btn btn-primary w-100">Create</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/blog/delete.html
{% extends "base.html" %}

{% block title %}Blog | Delete{% endblock title %}

{% block content %}
<div class="container mt-5" style="max-width: 48rem">
    <div class="card">
        <h3 class="card-header fw-bold text-center">Delete Post</h3>

        <div class="card-body">
            {% if user == post.author %}
                <p class="card-text">
                    Are you sure want to delete blog
                    <span class="fw-bold">{{ post.title }}</span>
                </p>

                <form action="{% url "blog:delete" post.pk %}" method="post">
                    {% csrf_token %}

                    <button type="submit" class="btn btn-primary w-100">Delete</button>
                </form>
            {% else %}
                <p class="card-text text-center">You are not authorised to delete this blog!</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}Blog - {{ post.title }} by {{ post.author }}{% endblock title %}

{% block content %}
<div class="container mt-5" style="max-width: 48rem">
    <div class="p-5 mb-5 bg-body-tertiary rounded-1">
        <h3 class="fs-3 fw-bold">{{ post.title }}</h3>

        <div class="d-flex justify-content-between text-body-secondary mb-3">
            <span>by {{ post.author }}</span>
            <span>{{ post.published_date }}</span>
        </div>

        <p class="fs-6">{{ post.text }}</p>
    </div>

    <div class="p-5 mb-4 bg-body-tertiary rounded-1">
        <h3 class="fw-bold">Comments</h3>

        {% if user.is_authenticated %}
            <form action="{% url "blog:detail" post.pk %}" method="post" class="mb-3">
                {% csrf_token %}

                <div class="mb-3">
                    <textarea name="text" id="id_text" rows="5" class="form-control" placeholder="your comment" required></textarea>
                </div>

                <button type="submit" class="btn btn-primary w-100">Create</button>
            </form>

        {% else %}
            <p>Please <a href="{% url "user:login" %}" class="link-primary link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">login</a> to comment.</p>
        {% endif %}

        <div class="border-top border-1">
            {% for comment in comments %}
                <div class="card mt-3">
                    <div class="card-body text-bg-tertiary">
                        <h5 class="fw-bold">{{ comment.user.username }}</h5>
                        <p class="card-text">{{ comment.text }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/draft.html
{% extends 'base.html' %}

{% block title %}Blog - {{ post.title }} by {{ post.author }}{% endblock title %}

{% block content %}
<div class="container mt-5" style="max-width: 48rem">
    <div class="p-5 mb-4 bg-body-tertiary rounded-1">
        <h3 class="fs-3 fw-bold">{{ post.title }}</h3>

        <div class="d-flex justify-content-between text-body-secondary mb-3">
            <span>by {{ post.author }}</span>
            <span>{{ post.published_date }}</span>
        </div>

        <p class="fs-6">{{ post.text }}</p>

        <form action="{% url "blog:draft" %}" method="post">

        </form>
    </div>
</div>
{% endblock content %}

templates/blog/list.html
{% extends 'base.html' %}

{% block title %}Blog Posts{% endblock title %}

{% block content %}
    <div class="container py-4" style="max-width: 64rem;">
        <h1 class="text-center border-bottom pb-3">Blogs</h1>
        <div class="container">
        {% for post in posts %}
            <div class="card mt-4">
                <div class="card-body">
                    <h3 class="card-title">{{ post.title }}</h3>
                    <p class="card-subtitle mb-2 text-body-secondary">{{ post.published_date }}  &vert; by <span>{{ post.author }}</span></p>
                    <p class="card-text">{{ post.text|truncatechars:255 }}</p>
                    <a href="{% url 'blog:detail' post.pk %}" class="card-link btn btn-primary">Read</a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

templates/blog/post_draft_list.html
<!DOCTYPE html>
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container">
        <h1>Drafts</h1>
            {% for post in DraftL %}
                {% if not post.published_date %}
                    <div class="post-draft">
                        <hr>
                        <p class="createdate">{{ post.creation_date }}</p>
                        <h2 class="post-title">{{ post.title }}</h2>

                        {% if user.is_authenticated %}
                        <div class="butt">
                            <div class="btn-left">
                                <a href="{% url 'blog:post_publish' pk=post.pk %}" class="btn btn-primary">Publish</a>
                            </div>
                            <div class="btn-right">
                                <a href="{% url 'blog:post_update' pk=post.pk %}" class="btn btn-warning "><span class="glyphicon glyphicon-edit"></span></a>
                                <a href="{% url 'blog:post_delete' pk=post.pk %}" class="btn btn-danger  "><span class="glyphicon glyphicon-remove"></span></a>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
    </div>
{% endblock %}

templates/blog/update.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block title %}Blog | Update{% endblock title %}

{% block content %}
<div class="container mt-5" style="max-width: 48rem">
    <div class="card">

        <h3 class="card-header fw-bold text-center">Update blog</h3>

        <div class="card-body">
            {% if post.author == user %}
                <form action="{% url "blog:update" post.pk %}" method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <div class="form-text text-danger-emphasis">
                            {% for error in form.non_field_errors %}
                                <p class="w-100 text-start">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="id_title" class="form-text">Title</label>
                        <input type="text" name="title" id="id_title" value="{{ post.title }}" class="form-control" autocomplete="off" maxlength="{{ form.title.meta.maxlength }}" required>
                        <div id="id_title_errors" class="form-text text-danger-emphasis">
                            {% for error in form.title.errors %}
                                <p class="w-100 text-start">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="id_text" class="form-text">Content</label>
                        <textarea name="text" id="id_text" class="form-control" rows="12" required>{{ post.text }}</textarea>
                        <div id="id_text_errors" class="form-text text-danger-emphasis">
                            {% for error in form.text.errors %}
                                <p class="w-100 text-start">{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="mb-3">
                        <label for="id_status" class="form-text">Status</label>
                        <select name="status" id="is_status" class="form-select" value="{{ post.status }}">
                            <option value="DRAFT" {% if post.status == "DRAFT"%} selected {% endif %}>Draft</option>
                            <option value="PUBLISH" {% if post.status == "PUBLISH"%} selected {% endif %}>Publish</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary w-100">Update</button>
                </form>
            </div>

        {% else %}
            <p class="card-text text-center">You are not author of this post.</p>
        {% endif %}
    </div>
</div>
{% endblock %}