blog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("<int:pk>/", views.PostDetailView.as_view(), name="detail"),
    path("create/", views.PostCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.PostUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.PostDeleteView.as_view(), name="delete"),

    # url(r"^$", views.PostListView.as_view(), name="post_list"),
    # url(r"^about", views.AboutView.as_view(), name="about"),
    # url(r"^post/(?P<pk>\d+)/$",views.PostDetailView.as_view(),name="post_detail"),
    # url(r"^post/(?P<pk>\d+)/edit",views.PostUpdateView.as_view(),name="post_update"),
    # url(r"^post/(?P<pk>\d+)/delete",views.PostDeleteView.as_view(),name="post_delete"),
    # url(r"^post/create/$",views.PostCreateView.as_view(),name="post_create"),
    # url(r"^draft",views.DraftView.as_view(),name="draft"),
    # url(r"^post/(?P<pk>\d+)/comment",views.add_comment,name="comment"),
    # url(r"^comment/(?P<pk>\d+)/approve/$",views.comment_approve,name="comment_approve"),
    # url(r"^comment/(?P<pk>\d+)/remove/$",views.comment_remove,name="comment_remove"),
    # url(r"^post/(?P<pk>\d+)/publish/$",views.publish,name="post_publish")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include(("blog.urls", "blog"), namespace="blog")),
    path("user/", include(("user.urls", "user"), namespace="user")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("register/", views.UserRegistrationView.as_view(), name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
]

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class UserRegisterationForm(UserCreationForm):
    """Form for user registeration."""

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ("username", "email")


class UserLoginForm(AuthenticationForm):
    """User login form."""

user/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from . import forms
from blog.models import Post


class UserRegistrationView(CreateView):
    """New user registration."""

    template_name = "user/register.html"
    success_url = reverse_lazy("user:login")
    form_class = forms.UserRegisterationForm


class UserLoginView(LoginView):
    """User login view."""

    form_class = forms.UserLoginForm
    template_name = "user/login.html"
    redirect_authenticated_user = True


class UserLogoutView(LogoutView):
    """User logout view."""

    next_page = "blog:list"


class UserProfileView(DetailView):
    """User dashboard view."""

    model = User
    context_object_name = "user_obj"
    template_name = "user/profile.html"

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        if self.request.user == self.object:
            kwargs["posts"] = self.object.posts.all()
        else:
            kwargs["posts"] = self.object.posts.all().filter(status=Post.Status.PUBLISH)
        return kwargs

templates/user/dashboard.html
{% extends "base.html" %}

{% block title %}User Dashboard{% endblock title %}

{% block content %}
<div class="container pt-5">
    <h1 class="mb-">Welcome {{ user.username }}</h1>
    <div class="p-5 mb-4 bg-body-tertiary rounded-1" style="max-width: 64rem;">
        <h3 class="mb-3">Your blogs</h3>
        {% for post in posts %}
            <div class="card mt-3">
                <div class="card-body">

                    <h3 class="card-title">{{ post.title }}</h3>

                    <p class="">
                        {% if post.status == "PUBLISH" %}
                            <span class="badge text-bg-success">Published</span>
                            <span class="card-subtitle mb-2 text-body-secondary">{{ post.published_date }}</span>
                            {% else %}
                            <span class="badge text-bg-light">Draft</span>
                        {% endif %}
                    </p>

                    <p class="card-text">{{ post.text|truncatechars:255 }}</p>

                    <a href="{% url 'blog:detail' post.pk %}" class="card-link btn btn-primary">Read</a>
                    <a href="{% url 'blog:update' post.pk %}" class="card-link btn btn-secondary">Edit</a>
                    <a href="{% url 'blog:delete' post.pk %}" class="card-link btn btn-secondary">Delete</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/user/login.html
{% extends 'base.html' %}

{% block title %}Login | Blog{% endblock title %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center h-100 w-100" style="min-height: 100vh; min-witdh: 100vh;">
	<div class="card" style="width: 20rem;">

		<h3 class="card-header fw-bold text-center">Login to website</h3>

		<div class="card-body text-center">
			<form action="{% url 'user:login' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<div class="form-text text-danger-emphasis">
						{% for error in form.non_field_errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
				</div>

				<div class="mb-3">
					<label for="id_username" class="form-label w-100 text-start">Username</label>
					<input type="text" name="username" class="form-control" id="id_username" autocomplete="username" required>
					<div id="id_username_errors" class="form-text text-danger-emphasis">
						{% for error in form.username.errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
				</div>

				<div class="mb-3">
					<label for="id_password" class="form-label w-100 text-start">Password</label>
					<input type="password" name="password" class="form-control" id="id_password" autocomplete="password" required>
					<div id="id_password_errors" class="form-text text-danger-emphasis">
						{% for error in form.password.errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
				</div>

				<div class="mb-3 text-center">
					<a href="{% url "user:register" %}" class="link-primary link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">Not registered?</a>
				</div>

				<button type="submit" class="btn btn-primary w-100">Login</button>
			</form>
		</div>

	</div>
</div>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %}

{% block title %}{{ user_obj.username }}&apos; profile{% endblock title %}

{% block content %}
<div class="container pt-5">
    <h1 class="mb-">{{ user_obj.username|capfirst }}&apos; profile</h1>

    {% if user.is_authenticated and user_obj == user %}
        <a href="{% url "blog:create" %}" class="btn btn-secondary">Write</a>
        <form action="{% url "user:logout" %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary">Logout</button>
        </form>
    {% endif %}

    <div class="p-5 mb-4 bg-body-tertiary rounded-1" style="max-width: 64rem;">
        <h3 class="mb-3">Blogs</h3>
        {% for post in posts %}
            <div class="card mt-3">
                <div class="card-body">

                    <h3 class="card-title">{{ post.title }}</h3>

                    <p class="">
                        {% if post.status == "PUBLISH" %}
                            <span class="badge text-bg-success">Published</span>
                            <span class="card-subtitle mb-2 text-body-secondary">{{ post.published_date }}</span>
                        {% else %}
                            <span class="badge text-bg-light">Draft</span>
                        {% endif %}
                    </p>

                    <p class="card-text">{{ post.text|truncatechars:255 }}</p>

                    <a href="{% url 'blog:detail' post.pk %}" class="card-link btn btn-primary">Read</a>

                    {% if user.is_authenticated and user == post.author %}
                        <a href="{% url 'blog:update' post.pk %}" class="card-link btn btn-secondary">Edit</a>
                        <a href="{% url 'blog:delete' post.pk %}" class="card-link btn btn-danger">Delete</a>
                    {% endif %}
                </div>
            </div>
        {% empty%}
            <div>No blogs</div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}Register | blog{% endblock title %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center h-100 w-100" style="min-height: 100vh; min-witdh: 100vh;">
	<div class="card" style="width: 20rem;">

		<h3 class="card-header fw-bold text-center">Register to website</h3>

		<div class="card-body text-center">
			<form action="{% url 'user:register' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<div class="form-text text-danger-emphasis">
						{% for error in form.non_field_errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
				</div>

				<div class="mb-3">
					<label for="id_username" class="form-label w-100 text-start">Username</label>
					<input type="text" name="username" class="form-control" id="id_username" autocomplete="username" required>
					<div id="id_username_errors" class="form-text text-danger-emphasis">
						{% for error in form.username.errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
				</div>

				<div class="mb-3">
					<label for="id_email" class="form-label w-100 text-start">Email</label>
					<input type="email" name="email" class="form-control" id="id_email" autocomplete="email" required>
					<div id="id_email_errors" class="form-text text-danger-emphasis">
						{% for error in form.email.errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
				</div>

				<div class="mb-3">
					<label for="id_password1" class="form-label w-100 text-start">Password</label>
					<input type="password" name="password1" class="form-control" id="id_password1" autocomplete="password" required>
					<div id="id_password1_errors" class="form-text text-danger-emphasis">
						{% for error in form.password1.errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
				</div>

				<div class="mb-3">
					<label for="id_password2" class="form-label w-100 text-start">Confirm Password</label>
					<input type="password" name="password2" class="form-control" id="id_password2" autocomplete="password" required>
					<div id="id_password2_errors" class="form-text text-danger-emphasis">
						{% for error in form.password2.errors %}
							<p class="w-100 text-start">{{ error }}</p>
						{% endfor %}
					</div>
				</div>

				<div class="mb-3 text-center">
					<a href="{% url "user:login" %}" class="link-primary link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">Already registered?</a>
				</div>

				<button type="submit" class="btn btn-primary w-100">Register</button>
			</form>
		</div>

	</div>
</div>
{% endblock %}

{% comment %} {% block content %}
<div class="container">
    <h1>Create Your Account</h1>
    <form method="post" action="{% url 'user:register' %}">
        <ul class="errorlist"><li>A user with that username already exists.</li></ul>
        {% csrf_token %}

        <div>
            <label for="id_username">Username</label>
            <input type="text" name="username" id="id_username" required autocomplete="username" maxlength="{{ form.username.field.max_length }}">
        </div>

        <div>
            <label for="id_email">Email</label>
            <input type="email" name="email" id="id_email" required autocomplete="email">
        </div>

        <div>
            <label for="id_password1">Password</label>
            <input type="password" name="password1" id="id_password1" required>
        </div>

        <div>
            <label for="id_password2">Confirm Password</label>
            <input type="password" name="password2" id="id_password2" required>
        </div>

        <input type="submit" value="save">
    </form>
</div>
{% endblock content %} {% endcomment %}